[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]>=3.4",
            "scikit-build>=0.11.0", "cmake>=3.18", "ninja"]

[tool.setuptools_scm]
write_to = "dcm2niix/_dist_ver.py"
write_to_template = "__version__ = '{version}'\n"
