.\" Modified from man(1) of FreeBSD, the NetBSD mdoc.template and mdoc.samples
.\" See man mdoc for the short list of editing options
.Dd December 9, 2016     \" DATE
.Dt DCM2NIIX 1           \" Program name and manual section number
.Os BSD
.Sh NAME\" Section Header - required - don't modify
.Nm dcm2niix
.Nd convert DICOM images to NIFTI.
.Sh SYNOPSIS\" Section Header - required - don't modify
.Nm
.Op Ar options              \" [file]
.Ar source_directory                 \" Underlined argument - use .Ar anywhere to underline
.Sh COPYRIGHT          \" Section Header - required - don't modify
.Nm
is open source. The bulk of the code is covered by the BSD license. Some units are either public domain (nifti., miniz.c) or use the MIT license (ujpeg.cpp).
.Sh DESCRIPTION          \" Section Header - required - don't modify
.Nm
converts images from the DICOM format (popular for medical imaging) to the NIfTI format (popular with scientific tools).
.Sh OPTIONS          \" Section Header - required - don't modify
.Bl -tag -width -indent  \" Differs from above in tag removed
.It Fl b
BIDS sidecar (y/n, default n)
.It Fl f
filename (%a=antenna  (coil) number, %c=comments, %d=description, %e echo number, %f=folder name, %i ID of patient, %m=manufacturer, %n=name of patient, %p=protocol, %s=series number, %t=time, %u=acquisition number, %z sequence name; default '%p_%e_%4s')
.It Fl h
show help
.It Fl m
merge 2D slices from same series regardless of study time, echo, coil, orientation, etc. (y/n, default n)
.It Fl o
output directory (omit to save to input folder)
.It Fl s
single file mode, do not convert other images in folder (y/n, default n)
.It Fl t
text notes includes private patient details (y/n, default n)
.It Fl v
verbose (y/n, default n)
.It Fl x
crop (y/n, default n)
.It Fl z
output directory (omit to save to input folder)
.El                      \" Ends the list
.Sh SOURCE DIRECTORY\" Files used or created by the program
The
.Ar source_directory                 \" Underlined argument - use .Ar anywhere to underline
is the location of the DICOM images to be converted. The software will convert all DICOM images in the source folder and sub folders.
